# Generated by Django 3.1.4 on 2020-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialecticapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialecticapp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
