# Generated by Django 3.1.4 on 2020-12-08 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dialecticapp', '0003_auto_20201207_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialecticapp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialecticapp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
