# Generated by Django 3.1.4 on 2020-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialecticapp', '0004_auto_20201208_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialecticapp',
            name='updated',
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='beforeSleep',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='daytime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='evening',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='morning',
            field=models.CharField(max_length=50),
        ),
    ]
