# Generated by Django 3.1.4 on 2020-12-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialecticapp', '0005_auto_20201208_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialecticapp',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='dialecticapp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
