# Generated by Django 3.1.4 on 2020-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialecticapp', '0006_auto_20201208_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialecticapp',
            name='beforeSleep',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='daytime',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='evening',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='morning',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dialecticapp',
            name='night',
            field=models.CharField(max_length=15),
        ),
    ]
